[project]
name = "capi-blog"
version = "0.4.0"
description = "Blog Info Capibaribe"
authors = [
    {name = "henriquecapi", email = "henriquecapi@hotmail.com"}
]
requires-python = ">=3.13"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.13"
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
python-multipart = "*"
databases = {extras = ["aiosqlite", "postgresql"], version = "*"}
sqlalchemy = "*"
pyjwt = "*"
asyncpg = "*"
psycopg2-binary = "*"
pydantic-settings = "^2.14.1"
alembic = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
pytest = "*"
pytest-asyncio = "*"
httpx = "*"
pytest-mock = "*"

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 90
target-version = ["py313"]

[tool.pyrefly]
python_interpreter = "C:\\Users\\henri\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\capi-blog-ESUKy2CM-py3.13\\Scripts\\python.exe"
source_directories = ["src"]
